import {logo,PRODI,DOCS,state,isAdmin,esc,normalizeProdi} from './core.js'

export function landingHtml(){
  return `<div class="min-h-screen bg-[#f7f9fc]">
    <header class="border-b border-slate-200 bg-white">
      <div class="mx-auto flex max-w-6xl items-center gap-3 px-5 py-4 lg:px-8">
        ${logo('h-12 w-12')}
        <div>
          <div class="text-lg font-extrabold text-[#0f2747]">SIMASI</div>
          <div class="text-[11px] font-semibold text-slate-500">FMIPA • Universitas Sulawesi Barat</div>
        </div>
        <button data-action="open-login" class="ml-auto rounded-xl bg-[#0f2747] px-5 py-2.5 text-sm font-extrabold text-white hover:bg-[#173a64]">Login</button>
      </div>
    </header>
    <main class="mx-auto max-w-6xl px-5 py-10 lg:px-8 lg:py-14">
      <div class="mb-7">
        <p class="text-xs font-extrabold uppercase tracking-[.18em] text-emerald-700">Informasi Akademik</p>
        <h1 class="mt-2 text-3xl font-extrabold text-slate-900">Informasi Terbaru</h1>
        <p class="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Pengumuman dan informasi akademik terbaru FMIPA Universitas Sulawesi Barat.</p>
      </div>
      <div id="landingAnnouncements" class="grid gap-4 md:grid-cols-2">
        <div class="simasi-card p-5 text-sm text-slate-500">Memuat informasi terbaru...</div>
      </div>
    </main>
    <footer class="mt-10 border-t border-slate-200 bg-white">
      <div class="mx-auto flex max-w-6xl flex-col gap-2 px-5 py-6 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8">
        <span>SIMASI • FMIPA Universitas Sulawesi Barat</span>
        <button data-action="open-login" class="font-extrabold text-emerald-700">Masuk ke sistem</button>
      </div>
    </footer>
    ${loginModal()}
  </div>`
}

function loginModal(){
  return `<div id="loginModal" class="fixed inset-0 z-[800] hidden overflow-y-auto bg-slate-950/55 p-4 backdrop-blur-sm">
    <div class="mx-auto flex min-h-full max-w-md items-center justify-center py-8">
      <div class="w-full rounded-3xl bg-white p-7 shadow-2xl md:p-9">
        <div class="flex items-start justify-between gap-4">
          <div class="flex items-center gap-3">${logo('h-12 w-12')}<div><p class="text-lg font-extrabold text-[#0f2747]">SIMASI</p><p class="text-[11px] text-slate-500">FMIPA Unsulbar</p></div></div>
          <button data-action="close-login" class="rounded-xl border px-3 py-2 font-bold">✕</button>
        </div>
        <div class="mt-7"><p class="text-xs font-extrabold uppercase tracking-[.16em] text-emerald-700">Autentikasi</p><h2 class="mt-2 text-2xl font-extrabold">Masuk ke Sistem</h2></div>
        <form id="loginForm" class="mt-6 space-y-4">
          <div><label class="mb-2 block text-sm font-bold">NIM / Email</label><input id="loginId" required autocomplete="username" class="w-full rounded-xl border border-slate-200 px-4 py-3.5" placeholder="Masukkan NIM atau email"></div>
          <div><label class="mb-2 block text-sm font-bold">Password</label><input id="loginPassword" type="password" required autocomplete="current-password" class="w-full rounded-xl border border-slate-200 px-4 py-3.5" placeholder="Masukkan password"></div>
          <button class="w-full rounded-xl bg-emerald-600 px-5 py-3.5 font-extrabold text-white hover:bg-emerald-700">Masuk</button>
        </form>
        <div id="loginError" class="mt-4 hidden rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"></div>
        <button id="forgotPassword" class="mt-5 w-full text-center text-xs font-extrabold text-emerald-700">Lupa password?</button>
      </div>
    </div>
  </div>`
}

export function privateShell(){
  const admin=isAdmin(),name=state.profile?.full_name||state.user?.email||'Pengguna',initial=name.charAt(0).toUpperCase()
  return `<div class="min-h-screen bg-[#f7f9fc]">
    <div id="mobileOverlay" class="fixed inset-0 z-40 hidden bg-slate-950/50 lg:hidden"></div>
    <aside id="sidebar" class="simasi-sidebar fixed inset-y-0 left-0 z-50 flex w-72 -translate-x-full flex-col text-white transition lg:translate-x-0">
      <div class="flex h-20 items-center border-b border-white/10 px-5">${logo('h-12 w-12')}<div class="ml-3 min-w-0"><p class="text-lg font-extrabold">SIMASI</p><p class="truncate text-[10px] text-slate-300">FMIPA • Universitas Sulawesi Barat</p></div><button data-action="close-menu" class="ml-auto lg:hidden">✕</button></div>
      <nav class="custom-scroll flex-1 overflow-y-auto p-4">${admin?adminNav():studentNav()}</nav>
      <div class="border-t border-white/10 p-4"><div class="flex items-center rounded-2xl bg-white/5 p-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500 font-extrabold">${esc(initial)}</div><div class="ml-3 min-w-0"><p class="truncate text-sm font-bold">${esc(name)}</p><p class="text-[10px] text-slate-400">${esc(state.profile?.role||'')}</p></div></div></div>
    </aside>
    <div class="private-shell min-h-screen lg:pl-72">
      <header class="sticky top-0 z-30 flex h-20 items-center border-b border-slate-200 bg-white/95 px-4 backdrop-blur md:px-8"><button data-action="open-menu" class="mr-3 rounded-xl border p-2 lg:hidden">☰</button><div><p id="pageEyebrow" class="text-xs font-extrabold uppercase tracking-[.16em] text-emerald-700">SIMASI</p><h1 id="pageTitle" class="mt-1 text-lg font-extrabold md:text-xl">Dashboard</h1></div><div class="ml-auto hidden text-right sm:block"><p class="max-w-48 truncate text-sm font-bold">${esc(name)}</p><p class="text-[10px] text-slate-500">${esc(state.profile?.role||'')}</p></div><div class="ml-3 flex h-10 w-10 items-center justify-center rounded-xl bg-[#0f2747] font-extrabold text-white">${esc(initial)}</div></header>
      <main id="privateMain" class="p-4 md:p-6 xl:p-8"></main>
    </div>
    ${passwordModal()}
  </div>`
}

function adminNav(){return `<p class="px-3 py-2 text-[10px] font-bold uppercase tracking-[.2em] text-slate-400">Administrator</p><button data-page="admin-dashboard" class="simasi-nav">▦ Dashboard Admin</button><button data-page="admin-registrations" class="simasi-nav">☷ Monitoring Pendaftar</button><button data-page="admin-import" class="simasi-nav">⇧ Import Data Mahasiswa</button><button data-page="admin-users" class="simasi-nav">♙ Pengelolaan User</button><div class="my-4 border-t border-white/10"></div><button class="simasi-nav disabled" disabled>▤ Manajemen Kuliah <span class="ml-auto rounded-full bg-white/10 px-2 py-0.5 text-[9px]">Segera</span></button><button class="simasi-nav disabled" disabled>✎ Logbook Skripsi <span class="ml-auto rounded-full bg-white/10 px-2 py-0.5 text-[9px]">Segera</span></button><div class="my-4 border-t border-white/10"></div><button data-action="logout" class="simasi-nav text-rose-200">← Keluar</button>`}
function studentNav(){return `<p class="px-3 py-2 text-[10px] font-bold uppercase tracking-[.2em] text-slate-400">Menu Utama</p><button data-page="student-dashboard" class="simasi-nav">▦ Dashboard</button><button data-page="seminar" class="simasi-nav">✓ Seminar Proposal/Seminar Hasil</button><div class="my-4 border-t border-white/10"></div><button class="simasi-nav disabled" disabled>▤ Manajemen Kuliah <span class="ml-auto rounded-full bg-white/10 px-2 py-0.5 text-[9px]">Segera</span></button><button class="simasi-nav disabled" disabled>✎ Logbook Skripsi <span class="ml-auto rounded-full bg-white/10 px-2 py-0.5 text-[9px]">Segera</span></button><div class="my-4 border-t border-white/10"></div><button data-action="logout" class="simasi-nav text-rose-200">← Keluar</button>`}
function passwordModal(){return `<div id="passwordModal" class="fixed inset-0 z-[950] hidden items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm"><div class="w-full max-w-lg rounded-3xl bg-white p-7 shadow-2xl"><div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-100 text-xl">🔐</div><h2 id="passwordTitle" class="mt-5 text-2xl font-extrabold">Ganti Password Pertama</h2><p id="passwordDesc" class="mt-2 text-sm leading-6 text-slate-500">Buat password baru minimal 8 karakter.</p><form id="passwordForm" class="mt-6 space-y-4"><input id="newPassword" type="password" minlength="8" required autocomplete="new-password" class="w-full rounded-xl border px-4 py-3" placeholder="Password baru"><input id="newPassword2" type="password" minlength="8" required autocomplete="new-password" class="w-full rounded-xl border px-4 py-3" placeholder="Ulangi password"><div id="passwordMsg" class="hidden rounded-xl border p-3 text-sm"></div><button class="w-full rounded-xl bg-emerald-600 px-5 py-3 font-extrabold text-white">Simpan Password Baru</button></form></div></div>`}

export function titleFor(page){const m={'admin-dashboard':['Dashboard Admin','Administrator SIMASI'],'admin-registrations':['Monitoring Pendaftar','Administrator SIMASI'],'admin-import':['Import Data Mahasiswa','Administrator SIMASI'],'admin-users':['Pengelolaan User','Administrator SIMASI'],'student-dashboard':['Dashboard','Mahasiswa SIMASI'],seminar:['Seminar Proposal/Seminar Hasil','Layanan Mahasiswa']};return m[page]||['SIMASI','FMIPA']}
export const statSkeleton=(label)=>`<div class="simasi-card p-5"><p class="text-xs font-bold uppercase text-slate-500">${label}</p><p class="mt-2 text-3xl font-extrabold">-</p></div>`
export function adminDashboardHtml(){return `<div class="simasi-hero rounded-3xl p-7 text-white"><p class="text-xs font-extrabold uppercase tracking-[.16em] text-emerald-200">Administrator SIMASI</p><h2 class="mt-3 text-3xl font-extrabold">Dashboard Admin</h2><p class="mt-2 text-sm text-slate-200">Ringkasan operasional layanan Seminar Proposal/Seminar Hasil FMIPA.</p></div><div id="adminStats" class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">${statSkeleton('Mahasiswa')}${statSkeleton('Total Pendaftar')}${statSkeleton('Menunggu Verifikasi')}${statSkeleton('Disetujui')}</div><div class="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div class="simasi-card overflow-hidden"><div class="flex items-center justify-between border-b p-5"><div><h3 class="font-extrabold">Pendaftaran Terbaru</h3><p class="mt-1 text-xs text-slate-500">5 pengajuan terakhir.</p></div><button data-page="admin-registrations" class="rounded-xl border px-4 py-2 text-xs font-extrabold">Lihat Semua</button></div><div class="overflow-x-auto"><table class="simasi-table min-w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-4 text-left">Mahasiswa</th><th class="p-4 text-left">Jenis</th><th class="p-4 text-left">Status</th><th class="p-4 text-left">Tanggal</th></tr></thead><tbody id="recentRegs"><tr><td colspan="4" class="p-8 text-center text-slate-500">Memuat...</td></tr></tbody></table></div></div><div class="simasi-card p-5"><h3 class="font-extrabold">Akses Cepat</h3><div class="mt-4 grid gap-3"><button data-page="admin-registrations" class="rounded-xl bg-[#0f2747] px-4 py-3 text-left text-sm font-extrabold text-white">Monitoring Pendaftar</button><button data-page="admin-import" class="rounded-xl border px-4 py-3 text-left text-sm font-extrabold">Import Data Mahasiswa</button><button data-page="admin-users" class="rounded-xl border px-4 py-3 text-left text-sm font-extrabold">Pengelolaan User</button></div></div></div>`}
export function registrationsHtml(){return `<div class="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p class="text-xs font-extrabold uppercase tracking-[.16em] text-emerald-700">Administrator SIMASI</p><h2 class="mt-2 text-2xl font-extrabold">Monitoring Pendaftar Seminar</h2><p class="mt-1 text-sm text-slate-500">Pantau kelengkapan berkas dan status verifikasi.</p></div><button data-action="refresh-registrations" class="rounded-xl border px-4 py-2 text-sm font-extrabold">↻ Refresh</button></div><div class="mt-6 simasi-card p-4"><div class="grid gap-3 md:grid-cols-4"><input id="regSearch" class="rounded-xl border px-3 py-2.5 text-sm" placeholder="Cari NIM / nama"><select id="regProdi" class="rounded-xl border px-3 py-2.5 text-sm"><option value="">Semua Prodi</option>${PRODI.map(p=>`<option>${p}</option>`).join('')}</select><select id="regType" class="rounded-xl border px-3 py-2.5 text-sm"><option value="">Semua Jenis</option><option>Seminar Proposal</option><option>Seminar Hasil</option></select><select id="regStatus" class="rounded-xl border px-3 py-2.5 text-sm"><option value="">Semua Status</option><option value="diajukan">Diajukan</option><option value="diverifikasi">Diverifikasi</option><option value="perbaikan">Perbaikan</option><option value="disetujui">Disetujui</option><option value="gagal_upload">Gagal Upload</option></select></div></div><div class="mt-4 simasi-card overflow-hidden"><div class="overflow-x-auto"><table class="simasi-table min-w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-4 text-left">Mahasiswa</th><th class="p-4 text-left">Prodi</th><th class="p-4 text-left">Jenis</th><th class="p-4 text-left">Berkas</th><th class="p-4 text-left">Status</th><th class="p-4 text-left">Aksi</th></tr></thead><tbody id="registrationRows"><tr><td colspan="6" class="p-8 text-center text-slate-500">Memuat...</td></tr></tbody></table></div></div>`}
export function importHtml(){return `<div class="simasi-hero rounded-3xl p-7 text-white"><p class="text-xs font-extrabold uppercase tracking-[.16em] text-emerald-200">Administrator SIMASI</p><h2 class="mt-3 text-3xl font-extrabold">Import Data Mahasiswa</h2><p class="mt-2 max-w-3xl text-sm leading-6 text-slate-200">Import NIM, Nama, dan Program Studi dari Excel/CSV atau PDF teks.</p></div><div class="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div class="simasi-card p-6"><div class="flex items-start justify-between gap-4"><div><h3 class="text-xl font-extrabold">1. Pilih File</h3><p class="mt-1 text-sm text-slate-500">.xlsx / .xls / .csv / .pdf berbasis teks</p></div><button data-action="download-template" class="rounded-xl border px-4 py-2 text-xs font-extrabold">Unduh Template CSV</button></div><label class="mt-5 block cursor-pointer rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 p-8 text-center hover:border-emerald-300 hover:bg-emerald-50"><input id="importFile" type="file" accept=".xlsx,.xls,.csv,.pdf" class="hidden"><div class="text-3xl">⇧</div><p class="mt-3 font-extrabold">Pilih Excel / PDF</p><p id="importFileName" class="mt-1 text-xs text-slate-500">Belum ada file.</p></label><div class="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-800"><b>Kolom wajib:</b> NIM, Nama, Program Studi. PDF scan gambar tidak diproses otomatis.</div></div><div class="simasi-card p-6"><h3 class="text-xl font-extrabold">2. Hasil Deteksi</h3><div class="mt-5 grid grid-cols-3 gap-3 text-center"><div class="rounded-2xl bg-slate-50 p-4"><p class="text-[10px] font-bold uppercase text-slate-500">Baris Valid</p><p id="importCount" class="mt-1 text-2xl font-extrabold">0</p></div><div class="rounded-2xl bg-slate-50 p-4"><p class="text-[10px] font-bold uppercase text-slate-500">Prodi</p><p id="importProdiCount" class="mt-1 text-2xl font-extrabold">0</p></div><div class="rounded-2xl bg-slate-50 p-4"><p class="text-[10px] font-bold uppercase text-slate-500">Login</p><p class="mt-1 text-sm font-extrabold text-emerald-700">NIM</p></div></div><button id="importExecute" disabled class="mt-5 w-full rounded-xl bg-emerald-600 px-5 py-3 font-extrabold text-white disabled:bg-slate-300">Import & Buat Akun Mahasiswa</button><div id="importResult" class="mt-4 hidden rounded-xl border p-4 text-sm"></div></div></div><div class="mt-6 simasi-card overflow-hidden"><div class="border-b p-5"><h3 class="font-extrabold">Preview Data</h3><p class="mt-1 text-xs text-slate-500">NIM yang sudah ada akan diperbarui tanpa reset password.</p></div><div class="overflow-x-auto"><table class="simasi-table min-w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-4 text-left">No.</th><th class="p-4 text-left">NIM</th><th class="p-4 text-left">Nama</th><th class="p-4 text-left">Program Studi</th></tr></thead><tbody id="importRows"><tr><td colspan="4" class="p-8 text-center text-slate-500">Belum ada data.</td></tr></tbody></table></div></div>`}
export function usersHtml(){return `<div class="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p class="text-xs font-extrabold uppercase tracking-[.16em] text-emerald-700">Administrator SIMASI</p><h2 class="mt-2 text-2xl font-extrabold">Pengelolaan User</h2><p class="mt-1 text-sm text-slate-500">Kelola akun mahasiswa, dosen, dan administrator.</p></div><button data-action="open-create-staff" class="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-extrabold text-white">+ Tambah Dosen / Staff</button></div><div class="mt-6 simasi-card p-4"><div class="grid gap-3 md:grid-cols-[1fr_220px]"><input id="userSearch" class="rounded-xl border px-3 py-2.5 text-sm" placeholder="Cari nama, NIM, email"><select id="userRole" class="rounded-xl border px-3 py-2.5 text-sm"><option value="">Semua Role</option><option value="mahasiswa">Mahasiswa</option><option value="staff">Staff</option><option value="dosen">Dosen</option><option value="admin">Admin</option></select></div></div><div class="mt-4 simasi-card overflow-hidden"><div class="overflow-x-auto"><table class="simasi-table min-w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-4 text-left">User</th><th class="p-4 text-left">NIM/Prodi</th><th class="p-4 text-left">Role</th><th class="p-4 text-left">Login Terakhir</th><th class="p-4 text-left">Aksi</th></tr></thead><tbody id="userRows"><tr><td colspan="5" class="p-8 text-center text-slate-500">Memuat...</td></tr></tbody></table></div></div>`}
export function studentDashboardHtml(){const name=state.profile?.full_name||'Mahasiswa',nim=state.profile?.nim||'-',prodi=state.profile?.prodi||'-';return `<div class="simasi-hero rounded-3xl p-7 text-white"><p class="text-xs font-extrabold uppercase tracking-[.16em] text-emerald-200">Dashboard Mahasiswa</p><h2 class="mt-3 text-3xl font-extrabold">Selamat datang, ${esc(name)}</h2><p class="mt-2 text-sm text-slate-200">Kelola proses Seminar Proposal/Seminar Hasil melalui akun pribadi Anda.</p></div><div class="mt-6 grid gap-4 md:grid-cols-3"><div class="simasi-card p-5"><p class="text-xs font-bold uppercase text-slate-500">NIM</p><p class="mt-2 text-xl font-extrabold">${esc(nim)}</p></div><div class="simasi-card p-5"><p class="text-xs font-bold uppercase text-slate-500">Program Studi</p><p class="mt-2 text-xl font-extrabold">${esc(prodi)}</p></div><div class="simasi-card p-5"><p class="text-xs font-bold uppercase text-slate-500">Status Akun</p><p class="mt-2 text-xl font-extrabold text-emerald-700">Aktif</p></div></div><div class="mt-6 grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><div class="simasi-card p-6"><h3 class="text-lg font-extrabold">Layanan Aktif</h3><p class="mt-2 text-sm leading-6 text-slate-500">Pendaftaran Seminar Proposal dan Seminar Hasil.</p><button data-page="seminar" class="mt-5 rounded-xl bg-emerald-600 px-5 py-3 text-sm font-extrabold text-white">Buka Pendaftaran Seminar</button></div><div class="simasi-card overflow-hidden"><div class="border-b p-5"><h3 class="font-extrabold">Riwayat Pendaftaran</h3></div><div id="studentHistory" class="p-5 text-sm text-slate-500">Memuat...</div></div></div>`}
export function seminarHtml(){const profileProdi=normalizeProdi(state.profile?.prodi||'');if(!state.selectedProdi&&profileProdi)state.selectedProdi=profileProdi;return `<div class="simasi-hero rounded-3xl p-7 text-white"><p class="text-xs font-extrabold uppercase tracking-[.16em] text-emerald-200">FMIPA Universitas Sulawesi Barat</p><h2 class="mt-3 text-3xl font-extrabold">Seminar Proposal/Seminar Hasil</h2><p class="mt-2 text-sm text-slate-200">Pilih jenis layanan, lengkapi identitas, lalu unggah 10 PDF wajib maksimal 2 MB per file.</p></div><div class="mt-6 simasi-card p-6"><h3 class="text-xl font-extrabold">Tahap 1 • Program Studi</h3><p class="mt-1 text-sm text-slate-500">Program studi mengikuti data akun hasil import admin.</p><div class="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">${PRODI.map(p=>`<button data-action="choose-prodi" data-prodi="${p}" class="prodi-card ${state.selectedProdi===p?'selected':''} ${profileProdi&&profileProdi!==p?'locked':''} rounded-2xl border-2 p-5 text-left"><div class="text-2xl">${p==='Matematika'?'∑':p==='Statistika'?'▥':p==='Aktuaria'?'↗':'⌘'}</div><h4 class="mt-3 font-extrabold">${p}</h4></button>`).join('')}</div></div><form id="seminarForm" class="mt-6 simasi-card p-6"><div><h3 class="text-xl font-extrabold">Tahap 2 • Data Pendaftaran</h3><p class="mt-1 text-sm text-slate-500">Prodi terpilih: <b class="text-emerald-700">${esc(state.selectedProdi||'-')}</b></p></div><div class="mt-5 grid gap-4 md:grid-cols-2"><input id="semNim" readonly value="${esc(state.profile?.nim||'')}" class="rounded-xl border bg-slate-50 px-4 py-3"><input id="semNama" readonly value="${esc(state.profile?.full_name||'')}" class="rounded-xl border bg-slate-50 px-4 py-3"></div><div class="mt-5 grid gap-3 md:grid-cols-2"><label class="rounded-2xl border bg-slate-50 p-4"><input type="radio" name="examType" value="Seminar Proposal" class="accent-emerald-600"> <b>Seminar Proposal</b></label><label class="rounded-2xl border bg-slate-50 p-4"><input type="radio" name="examType" value="Seminar Hasil" class="accent-emerald-600"> <b>Seminar Hasil</b></label></div><div class="mt-6 flex items-center justify-between"><h3 class="font-extrabold">Tahap 3 • Berkas Persyaratan</h3><span id="docProgress" class="rounded-full bg-slate-100 px-3 py-1 text-xs font-extrabold">0 / ${DOCS.length}</span></div><div class="mt-3 space-y-3">${DOCS.map(docRow).join('')}</div><div class="mt-6 flex flex-col gap-3 rounded-2xl bg-slate-50 p-4 md:flex-row md:items-center md:justify-between"><p id="semMessage" class="text-xs text-slate-500">Lengkapi seluruh persyaratan.</p><button id="submitSeminar" disabled class="rounded-xl bg-emerald-600 px-6 py-3 text-sm font-extrabold text-white disabled:bg-slate-300">Kirim Berkas Pendaftaran</button></div></form>`}
function docRow([key,label],i){return `<div class="doc-row rounded-2xl border bg-white p-4" data-key="${key}"><div class="flex flex-col gap-3 lg:flex-row lg:items-center"><div class="flex min-w-0 flex-1 items-start gap-3"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-xs font-extrabold text-emerald-700">${i+1}</span><div><b class="text-sm">${esc(label)}</b><p class="mt-1 text-[11px] text-slate-500">PDF • maksimal 2 MB</p></div></div><div class="flex flex-col gap-2 sm:flex-row lg:w-[46%]"><label class="flex-1 cursor-pointer rounded-xl border border-dashed bg-slate-50 px-3 py-3 text-center text-xs font-bold hover:border-emerald-300 hover:bg-emerald-50"><input class="doc-input hidden" data-key="${key}" type="file" accept="application/pdf,.pdf"><span class="file-name">Pilih PDF</span></label><button type="button" data-action="remove-doc" data-key="${key}" class="hidden rounded-xl border border-rose-100 px-3 py-2 text-xs font-bold text-rose-600">Hapus</button><span class="doc-badge self-center rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-500">Belum Diisi</span></div></div></div>`}
