@extends('layouts.app')
@section('title','Panel Staf')
@section('content')
<div class="page-head"><div><h1>Panel Dosen / Staf</h1><div class="muted">Review pengajuan, seminar, logbook, dan penilaian.</div></div></div>
<div class="grid" style="gap:22px">
<section class="card"><h2 style="margin-top:0">Pengajuan Skripsi</h2><div class="list">@forelse($skripsi as $item)<div class="list-item"><strong>{{ $item['nama'] }} · {{ $item['nim'] }}</strong><p>{{ $item['judul'] }}</p><form method="POST" action="{{ route('staff.skripsi.update',$item['id']) }}" class="form-grid">@csrf @method('PATCH')<div class="field"><label>Status</label><select class="select" name="status">@foreach(['menunggu','disetujui','revisi','ditolak'] as $s)<option value="{{ $s }}" @selected(($item['status']??'')===$s)>{{ ucfirst($s) }}</option>@endforeach</select></div><div class="field"><label>Catatan Dosen</label><input class="input" name="catatan_dosen" value="{{ $item['catatan_dosen']??'' }}"></div><div class="field full"><button class="btn btn-primary">Simpan Review</button></div></form></div>@empty<div class="muted">Belum ada pengajuan.</div>@endforelse</div></section>
<section class="card"><h2 style="margin-top:0">Pendaftaran Seminar</h2><div class="list">@forelse($seminar as $item)<div class="list-item"><strong>{{ $item['nama'] }} · {{ $item['jenis_ujian'] }}</strong><div class="muted">{{ $item['nim'] }} · {{ $item['prodi'] }}</div><form method="POST" action="{{ route('staff.seminar.update',$item['id']) }}" class="form-grid" style="margin-top:12px">@csrf @method('PATCH')<div class="field"><label>Status</label><select class="select" name="status">@foreach(['diajukan','diverifikasi','revisi','ditolak','selesai'] as $s)<option value="{{ $s }}" @selected(($item['status']??'')===$s)>{{ ucfirst($s) }}</option>@endforeach</select></div><div class="field"><label>Catatan Verifikator</label><input class="input" name="catatan_verifikator" value="{{ $item['catatan_verifikator']??'' }}"></div><div class="field full"><button class="btn btn-primary">Simpan Verifikasi</button></div></form></div>@empty<div class="muted">Belum ada pendaftaran.</div>@endforelse</div></section>
<section class="card"><h2 style="margin-top:0">Review Logbook</h2><div class="list">@forelse($logbook as $item)<div class="list-item"><strong>{{ $item['nim']??'Mahasiswa' }} · {{ $item['tanggal'] }}</strong><p>{{ $item['uraian'] }}</p>@if(!empty($item['file_url']))<a href="{{ $item['file_url'] }}" target="_blank" rel="noopener" style="color:#047857;font-weight:700">Buka tautan revisi ↗</a>@endif<form method="POST" action="{{ route('staff.logbook.review',$item['id']) }}" class="form-grid" style="margin-top:12px">@csrf<div class="field"><label>Status</label><select class="select" name="status_approval">@foreach(['Menunggu','Disetujui','Revisi'] as $s)<option value="{{ $s }}" @selected(($item['status_approval']??'')===$s)>{{ $s }}</option>@endforeach</select></div><div class="field"><label>Catatan</label><input class="input" name="catatan_dosen" value="{{ $item['catatan_dosen']??'' }}"></div><div class="field full"><button class="btn btn-primary">Simpan Review</button></div></form></div>@empty<div class="muted">Belum ada logbook.</div>@endforelse</div></section>
<section class="card"><h2 style="margin-top:0">Input / Perbarui Nilai</h2><form method="POST" action="{{ route('staff.nilai.save') }}" class="form-grid">@csrf<div class="field full"><label>Mahasiswa</label><select class="select" id="studentSelect" name="mahasiswa_id" required><option value="">Pilih mahasiswa</option>@foreach($mahasiswa as $m)<option value="{{ $m['id'] }}" data-nim="{{ $m['nim'] }}" data-nama="{{ $m['nama'] }}" data-prodi="{{ $m['prodi'] }}">{{ $m['nama'] }} · {{ $m['nim'] }}</option>@endforeach</select></div><input type="hidden" name="nim" id="nilaiNim"><input type="hidden" name="nama" id="nilaiNama"><input type="hidden" name="prodi" id="nilaiProdi"><div class="field"><label>Proposal</label><input class="input" type="number" step="0.01" min="0" max="100" name="nilai_proposal"></div><div class="field"><label>Bimbingan</label><input class="input" type="number" step="0.01" min="0" max="100" name="nilai_bimbingan"></div><div class="field"><label>Hasil</label><input class="input" type="number" step="0.01" min="0" max="100" name="nilai_hasil"></div><div class="field"><label>Ujian</label><input class="input" type="number" step="0.01" min="0" max="100" name="nilai_ujian"></div><div class="field"><label>Status Sidang</label><select class="select" name="status_sidang"><option>Siap Sidang</option><option>Lulus</option><option>Revisi</option><option>Tidak Lulus</option></select></div><div class="field" style="justify-content:end"><button class="btn btn-primary">Simpan Nilai</button></div></form><h3>Nilai Tersimpan</h3><div class="mobile-cards" style="display:flex">@forelse($nilai as $n)<div class="mobile-card"><strong>{{ $n['nama'] }} · {{ $n['nim'] }}</strong><div>Nilai akhir: <b>{{ $n['nilai_akhir']??'-' }}</b> · {{ $n['status_sidang'] }}</div></div>@empty<div class="muted">Belum ada nilai.</div>@endforelse</div></section>
</div>
@endsection
@push('scripts')<script>const s=document.getElementById('studentSelect');s?.addEventListener('change',()=>{const o=s.options[s.selectedIndex];document.getElementById('nilaiNim').value=o.dataset.nim||'';document.getElementById('nilaiNama').value=o.dataset.nama||'';document.getElementById('nilaiProdi').value=o.dataset.prodi||'';});</script>@endpush
