@extends('layouts.app')
@section('title','Seminar Proposal/Seminar Hasil')
@section('content')
<div class="page-head"><div><span class="eyebrow">PENDAFTARAN AKADEMIK</span><h1>Seminar Proposal/Seminar Hasil</h1><div class="muted">Persyaratan dapat dilihat tanpa login. Mahasiswa login saat akan melengkapi dan mengirim pendaftaran.</div></div></div>
<section class="card requirements-card"><div class="requirements-head"><div><h2>Persyaratan Berkas Mahasiswa</h2><p>Siapkan seluruh dokumen berikut sebelum mengisi formulir.</p></div><div class="upload-rule"><strong>PDF</strong><span>Maks. 2 MB/file</span></div></div><div class="requirements-grid">@foreach($docs as $key=>$label)<div class="requirement-item"><span class="req-no">{{ $loop->iteration }}</span><div><strong>{{ $label }}</strong>@if($key==='pas_foto')<small>Satukan 2 lembar pas foto dalam satu file PDF.</small>@else<small>Wajib diunggah dalam format PDF.</small>@endif</div></div>@endforeach</div></section>
@if(!$authenticated)
<section class="card login-gate"><div class="gate-icon">◎</div><div><h2>Login untuk mulai mengisi</h2><p class="muted">Setelah login, Anda akan kembali ke halaman ini dan formulir pendaftaran akan terbuka.</p></div><a class="btn btn-primary" href="{{ route('login',['next'=>'/seminar']) }}">Login Mahasiswa</a></section>
@else
<section class="card" style="margin-top:20px"><div class="section-title"><div><h2>Formulir Pendaftaran</h2><p class="muted">Pastikan data identitas dan seluruh dokumen sudah benar sebelum dikirim.</p></div><span class="badge badge-success">Login aktif</span></div><form method="POST" action="{{ route('seminar.store') }}" enctype="multipart/form-data">@csrf<div class="form-grid"><div class="field"><label>NIM</label><input class="input" name="nim" value="{{ old('nim',session('simasi_profile.nim')) }}" required></div><div class="field"><label>Nama</label><input class="input" name="nama" value="{{ old('nama',session('simasi_profile.full_name')) }}" required></div><div class="field"><label>Program Studi</label><select class="select" name="prodi" required><option value="">Pilih Program Studi</option>@foreach(['Matematika','Statistika','Aktuaria','Bioteknologi'] as $prodi)<option value="{{ $prodi }}" @selected(old('prodi',session('simasi_profile.prodi'))===$prodi)>{{ $prodi }}</option>@endforeach</select></div><div class="field"><label>Jenis Seminar</label><select class="select" name="jenis_ujian" required><option value="Seminar Proposal" @selected(old('jenis_ujian')==='Seminar Proposal')>Seminar Proposal</option><option value="Seminar Hasil" @selected(old('jenis_ujian')==='Seminar Hasil')>Seminar Hasil</option></select></div></div><div class="upload-banner"><strong>Ketentuan unggah</strong><span>Semua berkas wajib PDF dan maksimal 2 MB per file. Pendaftaran tidak dapat dikirim jika ada dokumen yang belum lengkap.</span></div><div class="document-upload-list">@foreach($docs as $key=>$label)<div class="doc-upload"><div class="doc-label"><span class="req-no">{{ $loop->iteration }}</span><div><strong>{{ $label }}</strong><small>PDF · maksimal 2 MB</small></div></div><div class="field"><input class="input file-input" type="file" name="documents[{{ $key }}]" accept="application/pdf,.pdf" required></div></div>@endforeach</div><input type="hidden" name="pas_foto_jumlah" value="2"><button class="btn btn-primary submit-wide" type="submit">Kirim Pendaftaran Seminar</button></form></section>
<section class="card" style="margin-top:20px"><h2 style="margin-top:0">Riwayat Pendaftaran</h2><div class="table-wrap"><table class="table"><thead><tr><th>Jenis</th><th>Program Studi</th><th>Status</th><th>Tanggal</th></tr></thead><tbody>@forelse($registrations as $item)<tr><td>{{ $item['jenis_ujian'] }}</td><td>{{ $item['prodi'] }}</td><td><span class="badge badge-warning">{{ ucfirst($item['status']) }}</span></td><td>{{ substr($item['created_at']??'',0,10) }}</td></tr>@empty<tr><td colspan="4">Belum ada pendaftaran.</td></tr>@endforelse</tbody></table></div><div class="mobile-cards">@forelse($registrations as $item)<div class="mobile-card"><strong>{{ $item['jenis_ujian'] }}</strong><div class="muted">{{ $item['prodi'] }} · {{ substr($item['created_at']??'',0,10) }}</div><div style="margin-top:8px"><span class="badge badge-warning">{{ ucfirst($item['status']) }}</span></div></div>@empty<div class="muted">Belum ada pendaftaran.</div>@endforelse</div></section>
@endif
@endsection
