<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','SIMASI') · FMIPA Unsulbar</title><link rel="stylesheet" href="{{ asset('css/app.css') }}"></head>
<body>
@php($authenticated=session()->has('simasi_access_token'))
@php($role=$authenticated?session('simasi_profile.role','mahasiswa'):'guest')
<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">SI</div><div><strong>SIMASI</strong><small>FMIPA Unsulbar</small></div></div><div class="nav-title">Menu utama</div><nav>
<a class="nav-link {{ request()->routeIs('dashboard')?'active':'' }}" href="{{ route('dashboard') }}"><span class="nav-icon">⌂</span>Dashboard</a>
<a class="nav-link {{ request()->routeIs('seminar.*')?'active':'' }}" href="{{ route('seminar.index') }}"><span class="nav-icon">▣</span>Seminar Proposal/Seminar Hasil</a>
<span class="nav-link nav-disabled"><span class="nav-icon">✓</span>Manajemen Kuliah <span class="coming">Nanti</span></span>
<span class="nav-link nav-disabled"><span class="nav-icon">✎</span>Pengajuan Skripsi <span class="coming">Nanti</span></span>
<span class="nav-link nav-disabled"><span class="nav-icon">☷</span>Logbook <span class="coming">Nanti</span></span>
<span class="nav-link nav-disabled"><span class="nav-icon">▤</span>Laporan & Nilai <span class="coming">Nanti</span></span>
</nav><div class="sidebar-user">@if($authenticated)<strong>{{ session('simasi_profile.full_name',session('simasi_email')) }}</strong><small>{{ ucfirst($role) }} · {{ session('simasi_profile.prodi','FMIPA') ?: 'FMIPA' }}</small><form method="POST" action="{{ route('logout') }}" style="margin-top:12px">@csrf<button class="btn btn-secondary" style="width:100%" type="submit">Keluar</button></form>@else<strong>Informasi Publik</strong><small>Login hanya diperlukan saat mengisi pendaftaran.</small><a class="btn btn-primary" style="width:100%;margin-top:12px" href="{{ route('login',['next'=>'/seminar']) }}">Login Mahasiswa</a>@endif</div></aside>
<main class="main"><header class="topbar"><div style="display:flex;align-items:center;gap:12px"><button class="mobile-menu" type="button" id="menuBtn">☰</button><strong class="topbar-title">SIMASI · FMIPA Universitas Sulawesi Barat</strong></div>@if($authenticated)<span class="badge badge-success">{{ ucfirst($role) }}</span>@else<a class="btn btn-soft" href="{{ route('login',['next'=>'/seminar']) }}">Login</a>@endif</header><div class="content">@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if(session('error'))<div class="alert alert-error">{{ session('error') }}</div>@endif @if($errors->any())<div class="alert alert-error"><strong>Periksa kembali isian:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</div></main></div>
<nav class="bottom-nav compact"><a class="{{ request()->routeIs('dashboard')?'active':'' }}" href="{{ route('dashboard') }}"><span class="ico">⌂</span>Beranda</a><a class="{{ request()->routeIs('seminar.*')?'active':'' }}" href="{{ route('seminar.index') }}"><span class="ico">▣</span>Seminar</a>@if($authenticated)<form method="POST" action="{{ route('logout') }}">@csrf<button type="submit" class="bottom-action"><span class="ico">↪</span>Keluar</button></form>@else<a href="{{ route('login',['next'=>'/seminar']) }}"><span class="ico">◎</span>Login</a>@endif</nav>
<script>const sidebar=document.getElementById('sidebar'),btn=document.getElementById('menuBtn');btn?.addEventListener('click',()=>sidebar.classList.toggle('open'));document.addEventListener('click',e=>{if(innerWidth<=980&&sidebar.classList.contains('open')&&!sidebar.contains(e.target)&&e.target!==btn)sidebar.classList.remove('open')});</script>@stack('scripts')</body></html>
